[package]
name = "libviewer"
version = "0.2.0"
edition = "2021"

[lib]
name = "libviewer"
# "cdylib" is necessary to produce a shared library for Python to import from
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "59.1", features = ["pyarrow"] }
bytes = "1.11.1"
env_logger = "0.11.8"
futures = "0.3"
log = "0.4.28"
object_store = "0.13.2"
object_store_opendal = { git = "https://github.com/apache/opendal", rev = "a13911ca36d72379f1fd58d9eb46938bbe13a654" }
opendal = { git = "https://github.com/apache/opendal", rev = "a13911ca36d72379f1fd58d9eb46938bbe13a654", features = ["services-huggingface"] }
parquet = { version = "59.1", features = ["arrow", "async", "object_store"] }
pyo3 = { version = "^0.29", features = ["extension-module"] }
pyo3-async-runtimes = { version = "^0.29", features = ["tokio-runtime"] }
pyo3-log = "0.13.4"
tempfile = "3.20.0"
thiserror = "2.0.12"
tokio = "1.45"
url = "2.5.4"
